language: python
env: # These should match the tox env list
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=pypy
    - TOXENV=pypy3
install:
    - if [[ $TOXENV == py26 ]]; then pip install ordereddict; fi
    - pip install coveralls tox
script: tox
# Special snowflake.  Our tests depend on making real commits.
before_install:
  - git config --global user.name "Travis CI"
  - git config --global user.email "user@example.com"
  # Install git-lfs for a test
  - './get-git-lfs.py && export PATH="/tmp/git-lfs:$PATH"'
after_success:
    - coveralls
sudo: false
cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.pre-commit
        - /tmp/git-lfs
