environment:
    matrix:
        - TOXENV: py27
        - TOXENV: py37

install:
    - "SET PATH=C:\\Python37;C:\\Python37\\Scripts;%PATH%"
    - pip install tox

# Not a C# project
build: false

test_script: tox

cache:
  - '%LOCALAPPDATA%\pip\cache'
  - '%USERPROFILE%\.cache\pre-commit'
